spring:
  application:
    name: collector
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
  h2:
    console:
      enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
      defer-datasource-initialization: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761
