-- DROP TABLES
DROP TABLE employee IF EXISTS;
DROP TABLE salary IF EXISTS;

-- CREATE TABLES
CREATE TABLE employee (
                      emp_no INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                      first_name VARCHAR(50),
                      last_name VARCHAR(50),
                      gender VARCHAR(50),
                      birth_date DATE,
                      hire_date DATE
);

CREATE TABLE salary (
                      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                      emp_no INT,
                      salary DOUBLE,
                      from_date DATE,
                      to_date DATE,
                      FOREIGN KEY(emp_no) REFERENCES employee
);

-- FILL TABLES
INSERT INTO employee(emp_no, first_name, last_name, gender, birth_date, hire_date) values (1, 'Bruce', 'Wayne', 'male', '1990-02-05', '2013-12-12');
INSERT INTO employee(emp_no, first_name, last_name, gender, birth_date, hire_date) values (2, 'Gwen', 'Stacy', 'female', '2000-08-14', '2020-02-06');
INSERT INTO employee(emp_no, first_name, last_name, gender, birth_date, hire_date) values (3, 'Matt', 'Murdock', 'male', '1980-10-31', '2021-06-21');
INSERT INTO employee(emp_no, first_name, last_name, gender, birth_date, hire_date) values (4, 'Dinah', 'Drake', 'female', '1999-12-31', '2023-07-24');

INSERT INTO salary (id, emp_no, salary, from_date, to_date) VALUES (1, 1, 50000, '2013-12-12', '2020-02-04');
INSERT INTO salary (id, emp_no, salary, from_date, to_date) VALUES (2, 1, 65000, '2020-12-12', null);
INSERT INTO salary (id, emp_no, salary, from_date, to_date) VALUES (3, 2, 45000, '2020-02-06', null);
INSERT INTO salary (id, emp_no, salary, from_date, to_date) VALUES (4, 3, 35000, '2021-06-21', null);
INSERT INTO salary (id, emp_no, salary, from_date, to_date) VALUES (5, 4, 85000, '2023-07-24', null);